Resources:
  RealtimeTableDataSource:
    Type: 'AWS::AppSync::DataSource'
    Properties:
      ApiId: ${self:custom.appsyncId}
      Description: ${self:service}, Edu-pal
      ServiceRoleArn: { Fn::GetAtt: ['AppSyncDynamoDBRole', 'Arn'] }
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        AwsRegion: ${self:provider.region}
        TableName:
          Fn::ImportValue: RealtimeTableEdupal
      Name: RealtimeTable
