const { writeFile, readFile } = require('fs');
const { promisify } = require('util');
const { exec } = require('child_process');

const FILEPATH = './resources/shared-appsync/schema.graphql';

/**
 * Remove @aws_subscribe directive definition from final schema.
 * Missing directive in development causes linter and graphql-schema-utilities error because undefined
 * But directive is pre-defined in AWS AppSync so redefinition causes error
 * Add warning to not directly edit
 */
const cleanSchema = async () => {
  await promisify(exec)(
    `yarn run --silent graphql-schema-utilities -ds "{./src/template/**/*.graphql,./src/schema/**/*.graphql,./src/services/**/mutations/**/*.graphql,./src/services/**/queries/**/*.graphql}" -o "${FILEPATH}"`
  );
  const schema = await promisify(readFile)(FILEPATH, 'utf8');
  const schemaWithoutDirectives = [
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. RUN scripts/combineSchemas TO REGENERATE\n',
    ...schema.split('\n').filter((line) => !line.startsWith('directive')),
  ].join('\n');
  await promisify(writeFile)(FILEPATH, schemaWithoutDirectives, 'utf8');

  return schemaWithoutDirectives;
};

cleanSchema();
module.exports = cleanSchema;
